#!/usr/bin/env node
/**
 * Generated by clity. This file is plain JavaScript by design — see the
 * project's CONSTITUTION.md § 3 ("Generated code is plain JavaScript"). Fork
 * freely; the only runtime dependency is Commander, and the only data source
 * is `lib/operations.json` next to this file.
 */
'use strict'

const { Command, Option } = require('commander')
const path = require('node:path')
const fs = require('node:fs')

const runtime = require('../lib/runtime.js')
const spec = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'lib', 'operations.json'), 'utf8'))

const program = new Command()
// Commander writes its own error text to stderr before calling exitOverride.
// We replace that with our structured JSON, so silence the default channel.
program.configureOutput({ writeErr: () => {} })
program.showHelpAfterError(false)
program
  .name(spec.cliName)
  .description(spec.description || spec.title || spec.cliName)
  .version(spec.cliVersion, '-V, --version', 'Print the CLI version and exit')
  .addOption(new Option('--base-url <url>', 'Override the API base URL').default(spec.baseUrl))
  .addOption(new Option('--token <token>', 'Bearer token for authenticated requests'))
  .addOption(new Option('--api-key <key>', 'API key for authenticated requests'))
  .addOption(new Option('--pretty', 'Pretty-print JSON output (default: compact)'))

program.exitOverride((err) => {
  if (
    err.code === 'commander.help' ||
    err.code === 'commander.helpDisplayed' ||
    err.code === 'commander.version'
  ) {
    process.exit(0)
  }
  runtime.writeError({ error: 'usage', message: err.message })
  process.exit(runtime.EXIT.USAGE)
})

program
  .command('describe [command]')
  .description('Print machine-readable JSON describing the CLI or a single command')
  .action((cmdName) => {
    if (cmdName) runtime.runDescribeOne(spec, cmdName)
    else runtime.runDescribe(spec)
  })

const auth = program
  .command('auth')
  .description('Manage saved auth credentials in ~/.' + spec.cliName + '/config.json')

auth
  .command('set')
  .description('Write --token and/or --api-key to the config file (non-interactive)')
  .option('--token <token>', 'Bearer token to save')
  .option('--api-key <key>', 'API key to save')
  .action((opts) => runtime.runAuthSet(spec, opts))

auth
  .command('show')
  .description('Print the path to the config file and whether each field is set')
  .action(() => runtime.runAuthShow(spec))

for (const op of spec.operations) {
  registerOperation(program, op, spec)
}

program.parseAsync(process.argv).catch((err) => {
  runtime.writeError({ error: 'internal', message: err && err.message ? err.message : String(err) })
  process.exit(runtime.EXIT.USAGE)
})

function registerOperation(program, op, spec) {
  const cmd = program.command(op.command)
  cmd.description(op.summary || op.description || `${op.method.toUpperCase()} ${op.path}`)

  for (const p of op.params) {
    const placeholder = `<${p.name}>`
    const flag = `--${p.flagName} ${placeholder}`
    const desc = describeParam(p)
    if (p.required) cmd.requiredOption(flag, desc)
    else cmd.option(flag, desc)
  }

  if (op.requestBody) {
    cmd.option('--body <json>', 'Request body as a JSON string')
    cmd.option('--body-file <path>', 'Read request body JSON from a file')
  }

  cmd.action(async (opts) => {
    try {
      await runtime.runOperation(spec, op, opts, program.opts())
    } catch (err) {
      runtime.exitForError(err)
    }
  })
}

function describeParam(p) {
  const bits = []
  if (p.description) bits.push(p.description.split('\n')[0])
  bits.push(`(${p.in} · ${p.type}${p.itemsType ? '<' + p.itemsType + '>' : ''})`)
  if (p.enum && p.enum.length) bits.push('enum: ' + p.enum.map(String).join('|'))
  return bits.join(' ')
}
