import type { CliOperation, CliSpec } from '../types.js'

/**
 * Templates for the generator's text output. Kept separate from emit/normalize
 * so changes to wording don't require touching the pipeline. See
 * CONSTITUTION.md § 4 (no runtime magic) — every template is plain string
 * concatenation, no engine.
 */

export function packageJson(spec: CliSpec): string {
  const pkg = {
    name: spec.cliName,
    version: spec.cliVersion,
    description: spec.description ?? `Agent-ready CLI for ${spec.title}`,
    bin: { [spec.cliName]: 'bin/cli.js' },
    main: 'bin/cli.js',
    files: ['bin', 'lib', 'AGENTS.md', 'README.md'],
    scripts: {
      start: 'node bin/cli.js',
    },
    engines: { node: '>=20' },
    dependencies: {
      commander: '^12.1.0',
    },
    keywords: ['openapi', 'cli', 'agents', 'clity-generated'],
    'clity-generated': {
      generator: spec.generator.name,
      generatorVersion: spec.generator.version,
      describeVersion: spec.describeVersion,
      specSource: spec.generator.specSource,
    },
  }
  return JSON.stringify(pkg, null, 2) + '\n'
}

export function readme(spec: CliSpec): string {
  const lines: string[] = []
  lines.push(`# ${spec.cliName}`)
  lines.push('')
  lines.push(spec.description ?? `Agent-ready CLI for ${spec.title}.`)
  lines.push('')
  lines.push('> Generated by [clity](https://github.com/luisgrandegg/clity). Read [`AGENTS.md`](./AGENTS.md) for the agent contract.')
  lines.push('')
  lines.push('## Install')
  lines.push('')
  lines.push('```bash')
  lines.push(`npx ${spec.cliName} describe`)
  lines.push('```')
  lines.push('')
  lines.push('## Usage')
  lines.push('')
  lines.push('```bash')
  lines.push(`# Discover the entire surface as JSON`)
  lines.push(`${spec.cliName} describe`)
  lines.push('')
  lines.push(`# Describe a single operation`)
  lines.push(`${spec.cliName} describe <command>`)
  lines.push('')
  lines.push(`# Run an operation (success → JSON on stdout, exit 0)`)
  lines.push(`${spec.cliName} <command> [--flag value ...]`)
  lines.push('')
  lines.push(`# Pretty-print for human reading`)
  lines.push(`${spec.cliName} <command> --pretty`)
  lines.push('```')
  lines.push('')

  if (spec.security.length > 0) {
    lines.push('## Auth')
    lines.push('')
    lines.push('Provide credentials via, in order of precedence:')
    lines.push('')
    lines.push(`1. \`--token <t>\` / \`--api-key <k>\` flag`)
    lines.push(`2. Environment variable \`${envPrefix(spec.cliName)}_TOKEN\` / \`${envPrefix(spec.cliName)}_API_KEY\``)
    lines.push(`3. \`~/.${spec.cliName}/config.json\` written by \`${spec.cliName} auth set --token <t>\``)
    lines.push('')
  }

  lines.push(`## Operations (${spec.operations.length})`)
  lines.push('')
  lines.push('| Command | Method | Path | Summary |')
  lines.push('|---|---|---|---|')
  for (const op of spec.operations) {
    const summary = (op.summary ?? '').replace(/\|/g, '\\|').slice(0, 80)
    lines.push(`| \`${op.command}\` | ${op.method.toUpperCase()} | \`${op.path}\` | ${summary} |`)
  }
  lines.push('')
  lines.push('Run `' + spec.cliName + ' describe` for the full machine-readable surface.')
  lines.push('')
  return lines.join('\n')
}

export function agentsMd(spec: CliSpec): string {
  return `# AGENTS.md — ${spec.cliName}

This CLI is generated by [clity](https://github.com/luisgrandegg/clity). Its
contract with agents is stable within a major version. Read once, cache the
\`describe\` output, and you have everything you need.

## Discovery

\`\`\`bash
${spec.cliName} describe              # full surface as JSON
${spec.cliName} describe <command>    # one operation as JSON
\`\`\`

The shape of \`describe\` output is documented at the clity repo. Key fields:

- \`operations[]\` — array of operations, each with \`command\`, \`method\`, \`path\`, \`summary\`, \`params\`, \`requestBody\`, \`responses\`, \`security\`
- \`security[]\` — declared security schemes, by name
- \`baseUrl\` — default base URL (override per-call with \`--base-url\`)

## I/O contract

| Channel | Contract |
|---|---|
| stdout (success) | Compact JSON, one document, trailing newline |
| stderr (failure) | \`{ "error": <string>, ... }\` JSON, one document, trailing newline |
| \`--pretty\` | Pretty-print stdout JSON. Off by default. |

## Exit codes

| Code | Meaning |
|---|---|
| 0 | Success |
| 1 | Usage / client error (bad flags, missing required input, invalid body JSON) |
| 2 | API error 4xx |
| 3 | Server error 5xx |
| 4 | Network error (DNS, refused, timeout) |

## Calling an operation

Every operation in \`describe\` becomes a subcommand of the same name. Path /
query / header parameters become flags by their \`flagName\` (kebab-case of
the OpenAPI name). Required params are enforced before any request is made.

Header parameters declared in the spec (\`in: header\`) are fully supported: the value passed via the corresponding flag is sent as an HTTP request header, and the header is omitted entirely when the flag is not provided.

\`\`\`bash
# Path / query / header param
${spec.cliName} <command> --pet-id 1 --status sold

# Request body (JSON only in v0.1)
${spec.cliName} <command> --body '{"name":"fluffy"}'
${spec.cliName} <command> --body-file ./body.json
\`\`\`

## Auth

Three sources, in order of precedence:

1. \`--token <t>\` / \`--api-key <k>\` flag
2. Environment variable \`${envPrefix(spec.cliName)}_TOKEN\` / \`${envPrefix(spec.cliName)}_API_KEY\`
3. Config file \`~/.${spec.cliName}/config.json\` written by \`${spec.cliName} auth set --token <t>\` (one-shot, non-interactive)

The CLI never prompts.

## Out of scope (v0.1)

- OAuth2 flows
- Multipart / file uploads
- Pagination helpers
- Response schema validation
- Shell completion
`
}

export function operationsJson(spec: CliSpec): string {
  return JSON.stringify(spec) + '\n'
}

export function envPrefix(cliName: string): string {
  return cliName.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()
}

export function operationSummary(op: CliOperation): string {
  return op.summary ?? op.description ?? `${op.method.toUpperCase()} ${op.path}`
}
